# Generated by Django 3.2.7 on 2021-09-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaDonvi', models.CharField(max_length=30)),
                ('TenDonVi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='QLTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC_TB', models.CharField(max_length=20)),
                ('Ten_TB', models.CharField(max_length=50)),
                ('Ten_Nguoidung', models.CharField(max_length=50)),
                ('MaDonvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.donvi')),
            ],
        ),
        migrations.CreateModel(
            name='Tenmien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thoigian', models.DateTimeField()),
                ('Ip_nguon', models.CharField(max_length=20)),
                ('Ip_dich', models.CharField(max_length=20)),
                ('MAC_dich', models.CharField(max_length=25)),
                ('DNS_string', models.CharField(max_length=50)),
                ('Dactinh', models.CharField(max_length=50)),
                ('MAC_TB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.qltb')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=None, null=True, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
                ('images', models.ImageField(upload_to='firstapp/images')),
                ('TenDonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.donvi')),
            ],
        ),
    ]
