# Generated by Django 3.2.7 on 2021-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_tenmien_nguoi_dung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_query_DNS',
        ),
        migrations.AddField(
            model_name='qltb',
            name='is_query_DNS',
            field=models.BooleanField(default=False),
        ),
    ]
